logging:
  level:
    com.GXDunzo: debug
    com.GXDunzo.LoggingAspect: error
    
  file.name : GXDunzo.log
  
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level){%magenta(%-5level)} %logger{36} - %msg%n"
    file :  "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    
    